[server]
address = "127.0.0.1"
port = 8501
headless = true

[browser]
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#087F8C"
backgroundColor = "#F8FAFC"
secondaryBackgroundColor = "#EAF0F5"
textColor = "#172B3A"
font = "sans serif"
